CREATE TABLE superstore_raw (
    row_id INT,
    order_id VARCHAR(50),
    order_date TEXT,
    ship_date TEXT,
    ship_mode TEXT,
    customer_id VARCHAR(50),
    customer_name TEXT,
    segment TEXT,
    country TEXT,
    city TEXT,
    state TEXT,
    postal_code VARCHAR(20),
    region TEXT,
    product_id VARCHAR(50),
    category TEXT,
    sub_category TEXT,
    product_name TEXT,
    sales NUMERIC,
    quantity INT,
    discount NUMERIC,
    profit NUMERIC
);